language: python
python:
    - "2.6"
    - "2.7"

env:
    DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

# install: "pip install --index-url=http://pypi.doubanio.com/simple/ -r requirements.txt --trusted-host=pypi.doubanio.com"
install: "pip install -r requirements.txt"
script: sh shell/restccnu_test.sh
