#-------------------- restccnu ------------------------
restccnu:
    build: .
    env_file:
        - restccnu.env
    command: gunicorn --name restccnu -b 0.0.0.0:5486 -w 2 wsgi:app
    ports:
        - "5486:5486"
    volumes:
        - .:/restccnu
    links:
        - redis1
        - redis2

#-------------------- celery --------------------------
celery:
    build: .
    env_file:
        - restccnu.env
    command: celery worker -A restccnu.workers.workers.celery --loglevel=INFO
    volumes:
        - .:/restccnu
    links:
        - redis3
        - redis1

#------------------- celery beats----------------------
celery_beats:
    build: .
    env_file:
        - restccnu.env
    command: celery -A restccnu.workers.workers.celery beat --loglevel=INFO
    volumes:
        - .:/restccnu
    links:
        - redis3
        - redis1

#------------------- redis servers---------------------
redis1:
    image: redis
    command: redis-server --port 6384  # 静态资源存储
    ports:
        - "7384:6384"
redis2:
    image: redis
    command: redis-server --port 6381  # 通知公告缓存
    ports:
        - "7381:6381"
redis3:
    image: redis
    command: redis-server --port 6383 # celery result backend
    ports:
        - "7383:6383"
