restccnu:
    build: .
    command: gunicorn --name restccnu -b 0.0.0.0:5060 -w 4 wsgi:app
    ports:
        - "5060:5060"
    volumes:
        - .:/restccnu
    links:
        - redis1
        - redis2

redis1:
    image: redis
    command: redis-server --port 6384  # 静态资源存储
    ports:
        - "6384:6384"
redis2:
    image: redis
    command: redis-server --port 6381  # 通知公告缓存
    ports:
        - "6381:6381"
